name: "Setup"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: "pnpm"

    - name: Install Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
