name: Changeset

on:
  pull_request:
    branches:
      - main

jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/setup

      # fails if there is no changeset present
      - name: Changeset
        run: pnpm run changeset:check
        continue-on-error: false
